name: tests

on: [push, pull_request]

jobs:
  build:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['7.3', '7.4', '8.0', '8.1']
        stability: [prefer-stable]
    steps:
      - name: Setup PHP Action
        uses: shivammathur/setup-php@v2
        with:
          extensions: intl, json, mbstring, xdebug, xml, pdo, sqlite, pdo_sqlite
          php-version: "${{ matrix.php-versions }}"
          tools: composer:v2
          coverage: xdebug
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Validate composer.json and composer.lock"
        run: "composer validate"
      - name: "Install dependencies"
        run: "composer install --prefer-dist --no-progress --no-suggest"
      - name: "Run test suite"
        run: "composer test"